<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCibuxm2\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCibuxm2/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerCibuxm2.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerCibuxm2\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerCibuxm2\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Cibuxm2',
    'container.build_id' => '5a21a6ff',
    'container.build_time' => 1534055481,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerCibuxm2');
